name: ArchDeploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: archlinux/base
    
    steps:
    - uses: actions/checkout@v1
    - name: Update arch
      run: |
        pacman -Syyu --noconfirm
    - name: Install base-devel
      run: |
        pacman -S --noconfirm base-devel
    - name: Install git
      run: |
        pacman -S --noconfirm git
