name: ArchDeploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: archlinux/base
    
    steps:
    - uses: actions/checkout@v1
    - name: Update arch
      run: |
        pacman -Syyu --noconfirm
    - name: Install base-devel, git and sudo
      run: |
        pacman -S --noconfirm base-devel sudo git
    - name: Setup build user
      run: |
        useradd builduser -m
        passwd -d builduser
        printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers

    - name: Build microdlang ldc
      run: |
        sudo -u builduser bash -c 'cd /tmp && git clone https://github.com/ErnyTech/auto-deploy.git && cd auto-deploy/packages/ldc && makepkg -s --noconfirm'
    - name: Move microdlang ldc
      run: |
        mkdir -p upload/ldc
        mv /tmp/auto-deploy/packages/ldc/*.tar.xz upload/ldc/ldc.tar.xz

    - uses: actions/upload-artifact@master
      with:
        name: microdlang-ldc
        path: upload/ldc
        
